# Generated by Django 4.1.7 on 2023-04-06 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=50)),
                ('fecha_de_transferencia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('equipo', models.CharField(default='Sin Equipo', max_length=200)),
                ('titular', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sitio_web', models.URLField()),
                ('contrato_total', models.BooleanField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App3.jugador')),
            ],
        ),
        migrations.DeleteModel(
            name='Jugadores',
        ),
    ]
