# Generated by Django 4.1.7 on 2023-04-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App3', '0002_equipo_jugador_manager_delete_jugadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='jugadores',
            field=models.CharField(default='', max_length=200),
        ),
    ]
