# Generated by Django 4.1.7 on 2023-04-08 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App3', '0004_representante_delete_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='fecha_de_transferencia',
            new_name='fecha_fundacion',
        ),
        migrations.RemoveField(
            model_name='representante',
            name='contrato_total',
        ),
        migrations.AddField(
            model_name='representante',
            name='jugadores_contratados',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App3.jugador'),
            preserve_default=False,
        ),
    ]
