# Generated by Django 4.1.7 on 2023-04-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App3', '0005_rename_fecha_de_transferencia_equipo_fecha_fundacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('golero', 'Golero'), ('defensa', 'Defensa'), ('mediocampista', 'Mediocampista'), ('delantero', 'Delantero')], default=0, max_length=50),
            preserve_default=False,
        ),
    ]
