# Generated by Django 4.1.7 on 2023-04-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App3', '0006_jugador_posicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='jugadores',
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='App3.equipo'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(choices=[('g', 'Golero'), ('d', 'Defensa'), ('m', 'Mediocampista'), ('f', 'Delantero')], max_length=1),
        ),
    ]
