# Generated by Django 4.1.7 on 2023-04-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App3', '0007_remove_equipo_jugadores_alter_jugador_equipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='region',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
