# Generated by Django 4.1.7 on 2023-04-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App3', '0008_equipo_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representante',
            name='jugadores_contratados',
        ),
        migrations.AddField(
            model_name='representante',
            name='jugadores_contratados',
            field=models.ManyToManyField(to='App3.jugador'),
        ),
    ]
