# Generated by Django 4.1.7 on 2023-04-28 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App3', '0011_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='User',
            new_name='user',
        ),
    ]
